### ISSUE TITLE
new device request: Google Pixel 6

### ISSUE THREAD

**Issue by Whyme3** [AXP-OS/issue-tracker#12]
# Required information
.
- Device vendor and model ->pixel 6
- Device codename (if known) -> oriole
- LineageOS device tree > couldn't find device tree but here the link for lineage builds https://download.lineageos.org/devices/oriole/builds
- Supported by DivestOS already? -> Yes
- I am willing to provide logs (requires either Matrix or Telegram) -> Yes

# Note
I want to start off telling you I'm a newbie. I know how to flash new Roms but don't kno how to pull logs but I'm willing to learn anything I need to. And help you testing your OS.

My email:  whyme87@disroot.org or derekkeefe@proton.me
 
My telegram: @derkman1

**Comment by steadfasterX** [comment]
Thx for your request @Whyme3 . Pls join the support [chan](https://github.com/AXP-OS/build/wiki#support) if you havent already. I am currently on vacation but will come back to you asap when there is a test build ready

**Comment by steadfasterX** [comment]
u can find a test build here: https://leech.binbash.rocks:8008/axp-unstable/
installation guide here: https://github.com/AXP-OS/build/wiki/oriole
would be great if you could test bootloader lock as well.. (see install guide)!
also test all core features pls: https://github.com/AXP-OS/build/wiki/Features
at least:

- magisk working
- microg working
- play store working
- F-Droid + Aurora working
- wireguard kernel support (after install give it root perms, enable kernel module in settings)

**Comment by steadfasterX** [comment]
@Whyme3 ig we can close this now? or do you plan to give it another try?

**Comment by steadfasterX** [comment]
if anyone wants to see that device let me know by re-opening this issue.
