### ISSUE TITLE
new device request

### ISSUE THREAD

**Issue by SayyadN** [AXP-OS/issue-tracker#14]
### Device vendor

Samsung 

### Device model

Galaxy A13 A137F

### Device codename

a13ve

### LineageOS device tree and/or WIKI page

https://github.com/badra639/twrp_samsung_a13ve

### Supported by DivestOS already?

no (see Notes-1)

### Prepared to support?

- [X] yes, I've joined

**Comment by steadfasterX** [comment]
Thanks for your request. Unfortunately your device is not supported by LineageOS nor divestOS. This means I will likely not able to build it. Is there any unofficial LineageOS available with a XDA thread? Without a valid device tree this aint gonna work anyways. The one you shared is for the recovery only.

**Comment by SayyadN** [comment]
no you can try

**Comment by steadfasterX** [comment]
If you find an unofficial build i might try. Otherwise not sorry.
