### ISSUE TITLE
new device request: Nokia 3.1

### ISSUE THREAD

**Issue by Ankitdas-1234** [AXP-OS/issue-tracker#16]
### Device vendor

Nokia

### Device model

3.1

### Device codename

ES2

### LineageOS device tree and/or WIKI page

https://github.com/nokia-mt6750/android_device_nokia_ES2

### Supported by DivestOS already?

no (see Notes-1)

### Prepared to support?

- [X] yes, I've joined

**Comment by steadfasterX** [comment]
thanks for your request. my main issue with that one is that there is absolute ZERO builds for this device nowhere (not at XDA or others). yes you found a device tree but that is very tiny I do not think that this will build or work at all at least. if you find someone who was able to create a successful build for this device re-open this issue and share the link to it, please. then I will check it again. thanks

**Comment by Ankitdas-1234** [comment]
I have got a kail linux rom for nokia 3.1
https://xdaforums.com/t/rom-official-kali-nethunter-for-the-nokia-3-1-android-9.4157681/

**Comment by steadfasterX** [comment]
yes but the device tree is missing, the manifest, all relevant parts. just the kernel source is linked which is not useful as this can be found elsewhere. the most promising org containing related stuff is https://github.com/nokia-mt6750 but as long as no one builds the all-over-the-world standard LineageOS for it this is too much work for a device I do not own even

**Comment by steadfasterX** [comment]
no sorry.

**Comment by Ankitdas-1234** [comment]
Then you can try just to make system.IMG for the device(without vendor.) My
system has kernel version 3.18,so I had not get any android 13 or 14 system
image compatible with my mobile.
                       The system image will also be good for other legacy
devices, which want to have the feel of your ROM.
