### ISSUE TITLE
new device request

### ISSUE THREAD

**Issue by Ankitdas-1234** [AXP-OS/issue-tracker#17]
### Device vendor

Nokia

### Device model

3.1 

### Device codename

ES2

### LineageOS device tree and/or WIKI page

https://github.com/nokia-mt6750/android_device_nokia_ES2

### Supported by DivestOS already?

no (see Notes-1)

### Prepared to support?

- [X] yes, I've joined

**Comment by steadfasterX** [comment]
Pls do not open new issues for the same device. There is a comment box if u want to add smth.

Closed as duplicate of #16
