### ISSUE TITLE
Galaxy a05

### ISSUE THREAD

**Issue by Shinewhine69** [AXP-OS/issue-tracker#18]
### Device vendor

Samsung

### Device model

Galaxy a05f

### Device codename

 SM-A055F

### LineageOS device tree and/or WIKI page

https://github.com/LineageOS/<FILL-IN>
https://wiki.lineageos.org/devices/<FILL-IN>

### Supported by DivestOS already?

no (see Notes-1)

### Prepared to support?

- [X] yes, I've joined

**Comment by steadfasterX** [comment]
sorry but there is no source for the device trees! if you find them (device and common) let me know. the [unofficial port ](https://xdaforums.com/t/rom-unofficial-port-a05m-mt6768-sm-a055f-sm-a055m-android-14-lineageos-21-for-the-samsung-galaxy-a05.4682104/) does not share any sources. feel free to re-open if you find a better documented port or contact him to provide the source trees
