### ISSUE TITLE
new device request: Samsung Galaxy S9 (starlte)

### ISSUE THREAD

**Issue by esnn6134** [AXP-OS/issue-tracker#22]
### Device vendor

Samsung

### Device model

Galaxy S9 SM-G960F

### Device codename

starlte

### LineageOS device tree and/or WIKI page

https://wiki.lineageos.org/devices/starlte/

### Supported by DivestOS already?

no (does not boot/fails to install)

### Prepared to support?

- [x] yes, I've joined

**Comment by steadfasterX** [comment]
this MIGHT be possible but the main issue here is that 

_The dos recovery fails to install and when installed via twrp it fails to boot_

so if you REALLY want to get this done it would require extensively debugging help from your site. I can create a debug build and give details on what and how etc of course.

Let me know if you can/want to.

**Comment by steadfasterX** [comment]
closed as no feedback.
