### ISSUE TITLE
new device request: Google Pixel 4a

### ISSUE THREAD

**Issue by duven87** [AXP-OS/issue-tracker#4]
# Required information

- Device vendor and model ->  Google Pixel 4a
- Device codename (if known) -> sunfish
- LineageOS device tree -> [_link_(*) ](https://download.lineageos.org/devices/sunfish/builds)
- Supported by DivestOS already? -> Yes
- I am willing to support (requires either Matrix or Telegram) -> Im not developer but ok as tester

# Note

_Currently not supported devices might get added but this won't work without your help. That means you have to admit to test new builds and maybe provide logs if something is not working as expected._

_(*)your request will likely get rejected if there is no official LOS reference_

**Comment by steadfasterX** [comment]
Device request state:

- [ ] update [AXP.OS manifest](https://github.com/AXP-OS/manifest)
- [ ] setup [vendor/firmware](https://code.binbash.rocks:8443/AXP.OS/vendor_firmware)
- [ ] setup [automation repo](https://github.com/sfX-android/automation_scripts/tree/ansible/roles/axp)
- [ ] setup semaphore
- [ ] compile
- [ ] if device is NOT supported by DOS: see "additional steps"
- [ ] test all AXP.OS [core features](https://github.com/AXP-OS/build/wiki/Features)
- [ ] if applicable: test bootloader re-lock
- [ ] add device to [the AXP.OS wiki](https://github.com/AXP-OS/build/wiki)
- [ ] provide a public beta version
- [ ] update website
- [ ] announce on XDA

additional steps (if device is NOT supported by DOS):

- [ ] setup kernel patching:
   - [ ] [cve-patcher](https://github.com/sfX-android/automation_scripts/tree/ansible/roles/axp/common/files/cve_fixup)
   - [ ] [defconfig](https://github.com/sfX-android/automation_scripts/blob/ansible/roles/axp/common/files/extend_dos/getDefconfig.patch)
   - [ ] fix boot issues by overwriting default CONFIGs (e.g. like [this](https://github.com/sfX-android/automation_scripts/blob/d20f7dce494c72e956eb4e7efde2c0705cb969b3/roles/axp/common/templates/divested.vars.j5y17lte.j2#L13C8-L13C28))
